[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false
evm_version = "cancun"
ffi = false

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[fuzz]
runs = 256

[profile.ci.fuzz]
runs = 2000
